### ISSUE TITLE
Remove unnecessary checks for API handles

### ISSUE THREAD

**Issue by elfring** [jpbruyere/vkChess#3]
[An extra check is not needed for a zero API handle](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#fundamentals-validusage-handles "Do I need to check for null before delete p?") in functions like the following.
* [vks::VulkanDevice](https://github.com/jpbruyere/vkChess/blob/74ccbd914eff74136f86debc48137a7b908e974b/base/VulkanDevice.cpp#L52 "Constructor for vks::VulkanDevice")
* [vks::vkRenderer::destroy](https://github.com/jpbruyere/vkChess/blob/32d4b40d859c1f69b045738ae571eeeaed6a52d5/src/vkrenderer.cpp#L22 "vks::vkRenderer::destroy function")

**Comment by jpbruyere** [comment]
The first point, you are right, testing buffer is not needed, thanks.
In the second point (vkRenderer::destroy) I don't see what you mean

**Comment by elfring** [comment]
The mentioned programming interfaces tolerate the passing of null pointers, don't they?
I do not see a need to repeat a corresponding sanity check there.

**Comment by jpbruyere** [comment]
Ok for the second point, but to be coherent, I've reset handles to NULL after destroy, thanks for your help.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/jpbruyere/vkChess/commit/c848a1d4d6dbe39de086798cc8ac0b5bc9077713 "Deletion of three redundant checks").
